### ISSUE TITLE
clickMenuItemById doesn't seem to work

### ISSUE THREAD

**Issue by Slapbox** [spaceagetv/electron-playwright-helpers#16]
If the `id` that `newproject` refers to [in the examples](https://github.com/spaceagetv/electron-playwright-helpers) is the same one found in the [Electron Examples](https://www.electronjs.org/docs/latest/api/menu#examples-1) it doesn't seem to work for us. 

It throws with `Error: Menu item with id 0 not found`

**Comment by Slapbox** [comment]
Thanks to the developers of this library by the way!

----

I was able to do this to find the correct `MenuItem`, but there's no way to click it except by `id` which doesn't seem to work.

This code finds my item, but how to click?

```

  const appMenu = await getApplicationMenu(electronApp);
  const foundItem = await findMenuItem(electronApp, 'label', 'Quit', appMenu);
```

**Comment by jjeff** [comment]
`clickMenuItemById()` allows you to click an Electron MenuItem based on its [menuItem.id property](https://www.electronjs.org/docs/latest/api/menu-item#menuitemid). This value can (and should) be set by the developer, but it should be unique.

So (just so we're on the same page) some pseudo code:

…in your main process:

```JS
const menuTemplate = [
// …stuff
{
  label: `Make Awesome Stuff Happen`, // <-- if you internationalize your app, this may change, so it's not a good key
  id: 'awesome', // <-- be sure to assign this so that you can test
  click: () => { awesome() }
}
// …stuff
]
```

…in your Playwrite script
```JS
// …launch the app

await clickMenuItemById(electronApp, 'awesome')

// …expect that the menu item has been clicked
```

Make sense? Is this helpful?

`clickMenuItemByLabel()` is problematic because labels don't need to be unique, and they could change with internationalization. `clickMenuItemByRole()` also doesn't need to be unique, and in a custom app, most menu items won't have a role.

**Comment by Slapbox** [comment]
Thanks for your reply @jjeff!

Surprisingly we're using the code as you've outlined but it doesn't seem to work in our case - **perhaps because the menu is assigned to the app's tray icon?** (my best theory)

A stripped down version of our app code looks like this. There's some silly looking things to keep the code I'm sharing as similar as possible to our actual code:

**App code:**

```js
  const appTray = new Tray(trayIcon);

  const contextMenuArray = []
  contextMenuArray.push(
    {
      id: 'quit', // Used to invoke via Playwright
      label: 'Quit',
      click: preQuitApp,
      selector: 'terminate:',
    }
  );

  const contextMenu = Menu.buildFromTemplate(contextMenuArray);
  appTray.setContextMenu(contextMenu);
  ```

and then

**Test code:**

```js
  await clickMenuItemById(electronApp, 'quit');
```

I also tried setting a different `id` value (the `'0'` mentioned in my first comment) to be sure there wasn't any issue with that particular value.

I don't think it should matter, but perhaps it does - we're testing on Linux.

I'm not sure what could be wrong here, but if you have any ideas, they'd be greatly appreciated - but even if not, thank you so much for your great work!

**Comment by jjeff** [comment]
Ahh! Okay. Hmm…

`clickMenuItemById()` is going to look for the menu item in the [Application Menu](https://www.electronjs.org/docs/latest/api/menu#menugetapplicationmenu), using the [`menu.getMenuItemById()` method](https://www.electronjs.org/docs/latest/api/menu#menugetmenuitembyidid).

Context menus are handled in a different way. I don't think that we can get to them via Electron. There really ought to be a `tray.getContextMenu()` as a counter to the [`tray.setContextMenu()`](https://www.electronjs.org/docs/latest/api/tray#traysetcontextmenumenu), but Electron doesn't have this. I'm guessing that there might be a way of hacking this, but it will be a challenge.

What I've done to test context menus in my app is to set them up with `ipcMain.handle()` return values, so that I can test them in my E2E code…

Something like this:

```JS
const appTray = new Tray(trayIcon);

  const contextMenuArray = []
  contextMenuArray.push(
    {
      id: 'quit', // Used to invoke via Playwright
      label: 'Quit',
      click: preQuitApp,
      selector: 'terminate:',
    }
  );

  const contextMenu = Menu.buildFromTemplate(contextMenuArray);
  appTray.setContextMenu(contextMenu);

  // to "see" the menu in your test
  ipcMain.handle('get-tray-menu' () => {
    return JSON.parse(JSON.stringify(contextMenu)) // <-- or contextMenuArray if that's easier…
  })

  // and/or, much simpler

  ipcMain.handle('pre-quit-app', preQuitApp)
```

You could then access these with `ipcMainInvokeHandler()` in your tests…

**Comment by Slapbox** [comment]
Hmm you know what, it turns out we already effectively have `ipcMain.handle('pre-quit-app', preQuitApp)` - so I think that will be our best bet. I guess this is a case of thinking myself into a corner. I appreciate you bailing me out with that insight!

Ideally I think this is something the `electron-playwright-helpers` should be able to access - but I understand there's really nothing to be done until/unless Electron adds `getContextMenu`.

I made an issue at https://github.com/electron/electron/issues/36929 asking for a `getContextMenu` helper.

Thanks again for your great work and friendly support @jjeff!

**Comment by jjeff** [comment]
I'm closing this for now. I've added a note in the documentation for `clickMenuItemById()` saying that this only works with the Application Menu. Please reopen if I've missed something.
