### ISSUE TITLE
Add support for electron-builder

### ISSUE THREAD

**Issue by andirsun** [spaceagetv/electron-playwright-helpers#4]
We at @webalys-hq are supporting an electron app + Next Js + Electron builder, I am the responsible of add test to desktop app.

I really like your library and I think we can work together in order to offer support for electron builder. I've tried the helpers library but it does not work with out code, so I think we can leave this issue open to start the conversation about it.

**Comment by jjeff** [comment]
I'm totally open to this. However, since I don't have much experience with Electron Builder, I don't know what would need to be added. Technically, this library should work with ANY builder for Electron, since it allows you to test a built Electron app. 

Do different builders structure their Electron apps differently? There are [comments in the `parseElectronApp()` function](https://github.com/spaceagetv/electron-playwright-helpers/blob/afd87657d473efa332504a0c1b19e8a0f7d18d99/src/find_parse_builds.ts#L182-L196) which outline the current assumptions about the structure of an Electron app on [Mac](https://github.com/spaceagetv/electron-playwright-helpers/blob/afd87657d473efa332504a0c1b19e8a0f7d18d99/src/find_parse_builds.ts#L182-L196), [Windows](https://github.com/spaceagetv/electron-playwright-helpers/blob/afd87657d473efa332504a0c1b19e8a0f7d18d99/src/find_parse_builds.ts#L227-L234), and [Linux](https://github.com/spaceagetv/electron-playwright-helpers/blob/afd87657d473efa332504a0c1b19e8a0f7d18d99/src/find_parse_builds.ts#L264-L271). But I had a hard time finding documentation on Electron build file structures, so I made some assumptions.

Other than that, [`findLatestBuild()`](https://github.com/spaceagetv/electron-playwright-helpers/blob/afd87657d473efa332504a0c1b19e8a0f7d18d99/src/find_parse_builds.ts#L12) was recently changed to allow an argument for the build directory. (It used to be hard-coded to `out`. Now that is the default.) Does this help with Electron Builder?

**Comment by Slapbox** [comment]
@jjeff I don't know if this is the problem everyone is having, but at least for us, `getLinuxExecutableName` is returning `unpacked` instead of `our-app` given a path like `out/dev/unpacked-linux-x64/our-app`.

**Comment by Slapbox** [comment]
Unfortunately after I got everything configured apparently correctly, it just hangs on `electron.launch` and never executes past that line, even though it starts the app up as expected.

**Comment by jjeff** [comment]
> Unfortunately after I got everything configured apparently correctly, it just hangs on `electron.launch` and never executes past that line, even though it starts the app up as expected.

Frustrating! Well, I'm rooting for you. Let me know if you can identify any changes to `electron-playwright-helpers` that would help it to work better with `electron-builder`.

The script does make a lot of guesses and assumptions. For instance, it's trying to gleen both the platform and the architecture from the directory and/or app name. On the Mac, we've got both x64 and arm64 architectures (and it looks like that will be happening on Windows more and more in the future). So you can't just assume that the platform will define the architecture. But I suppose we could have another platform value of `unknown` or something, rather than failing altogether.

But keep the feedback coming! I don't have much experience building with `electron-builder` – or building for Linux. But it would be great if this module could work for both!

**Comment by MatthijsBurgh** [comment]
I think the problem is in playwright. As I haven't been able to run an application build by `electron-builder`. Also without using the helpers in this project. Just no combination of electron executable, both the packed executable and the general electron executable, and main file I was able to get working. I have no clue which main files I have tried anymore.

**Comment by jjeff** [comment]
> I think the problem is in playwright. As I haven't been able to run an application build by `electron-builder`. Also without using the helpers in this project. Just no combination of electron executable, both the packed executable and the general electron executable, and main file I was able to get working. I have no clue which main files I have tried anymore.

Is there an `electron-builder` quickstart, template, or example repo out there somewhere? Some kind of minimal "Hello World" project that we could test against? I've done some quick searching and I can't find anything. I'm guessing there's just some basic difference in the ways that `electron-forge` and `electron-builder` bundle their apps. But I don't currently have a way to look at an `electron-builder` built app.

All that being said, it also should be possible to test against your unpackaged code, by pointing to your `main.js` file and using the Electron binary in your node_modules folder (which Playwright will do automatically), similar to the example in the [Playwright Electron documentation](https://playwright.dev/docs/api/class-electron). But maybe you're already doing that.

**Comment by MatthijsBurgh** [comment]
Yes, unpacked testing worked for me. Though I want to test packed code to be sure all the required files are packed correctly.

I am a bit busy, so I do not have time right away to look for a example. I will let you know when I have found something.

**Comment by MatthijsBurgh** [comment]
With a quick search I found this boilerplate repo: https://github.com/electron-userland/electron-webpack-quick-start

I haven't been able to test it for now. Also this week, testing this would be difficult for me.

**Comment by Slapbox** [comment]
@MatthijsBurgh I'm able to get it working by manually specifying an absolute path for `executablePath` like:

```js
electronApp = await electron.launch({
    args: [appInfo.main],
    executablePath:
      '/home/me/Documents/MyProject/release/dev/linux-unpacked/myproject',
  });
```

@jjeff Rather than electron-webpack-quick-start, I'd consider [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) which is much more recent and maintained.

The only real issue with supporting Electron-Builder seems to be that `appInfo.executable` is detected improperly in `parseElectronApp`. It should reach into `linux-unpacked` and grab the executable there, but instead it looks for a path something like this (maybe not exact, going from memory as I'm currently mid-`git bisect`) `/home/me/Documents/MyProject/release/dev/linux-unpacked/unpacked` (note last segment should be `myproject` not `unpacked`.

Thanks again for your fantastic work and let me know how I can be of help!

**Comment by jjeff** [comment]
@Slapbox So in [`parseElectronApp()`](https://github.com/spaceagetv/electron-playwright-helpers/blob/00fa57abf9bac6dfb66fa3af998888f66c0a2109/src/find_parse_builds.ts#L123) we're making A LOT of guesses, assumptions, and expectations. That is especially true for Linux. 

One of those assumptions is that the Linux file structure of a packaged app will look like this:

```JS
    // <buildDir>/ (the directory that your app will be distributed in)
    //   <appName> (executable)
    //   resources/
    //     app.asar (asar bundle) - or -
    //     app --- (untested - we're making assumptions here)
    //       package.json
    //       (your app structure)
``` 

I can't figure out where my `<buildDir>` is in your file path. Is that `dev`? Or `release`?

Maybe a  better question is: "How should the above structure be changed?"

Also, I recently added an [`example-project`](https://github.com/spaceagetv/electron-playwright-helpers/tree/main/example-project) to the project which acts as a test suite for `electron-playwright-helpers`. The tests are passing on GitHub's Ubuntu-based Actions runner. So I'm guessing that whatever changes you need might be specific to `electron-builder`… But that remains to be seen.

**Comment by Slapbox** [comment]
So my project outputs into `release/dev` or `release/prod` (not `electron-builder` specific)

`release/dev` contains the distributable executable files (AppImage/snap in this case), and the `linux-unpacked` folder (which would be your `buildDir`)

It's structured like this:

```
  linux-unpacked
      locales
      resources
      swiftshader
      ourapp // the executable file
  OurApp.AppImage
  OurApp.snap
```

I think the biggest problem assumption is that it doesn't anticipate that there's a level above `linux-unpacked` that contains the packed software.

Here's an image of the output from `electron-react-boilerplate` on Linux. The only difference for Mac/Windows is that they'll be called `win-unpacked` or (I think) `mac-unpacked` - and then of course the executable name ends with `.exe` on Windows

![image](https://user-images.githubusercontent.com/6835891/213052829-7d64381c-b5b2-41d1-ae46-4aff178cbc4c.png)

**Comment by baversjo** [comment]
my project worked well with `24.0.0-alpha.10`, on both windows and mac. On Linux however, I was getting an error that the executable was wrong. This was due to it referencing to the folder linux-unpacked (dist/linux-unpacked), instead of the executable (dist/linux-unpacked/app-name). Adding the name of the executable (app-name in below example) to the end off appInfo.executable got linux working for me. The path to main.js was correct for me without any modifications: `dist/linux-unpacked/resources/app.asar/main.js`.

"Solution":

```
    const latestBuild = findLatestBuild('dist/');
    const appInfo = parseElectronApp(latestBuild);

    if (process.platform === 'linux') {
        appInfo.executable += '/app-name';
    }
```

**Comment by Slapbox** [comment]
>  So how can we determine which file is the Linux executable? Is it the only file without a suffix? Is there another way to differentiate the file from the others in the directory?

That's an excellent question - especially since the name won't necessarily match the `package.json` name.

In KDE, the file is recognized by Dolphin file explorer as an executable, but I don't know2 how it's determining that. I ran Node's `fs.statSync` on the file but I didn't get any obvious clues about whether we can determine it that way:

![image](https://user-images.githubusercontent.com/6835891/214444637-dfa99658-393a-4954-9d35-daaea7f58ec9.png)

I'm guessing it's just determined by having the executable flag set - but it's not the only item in the folder that's an executable in that case - although the others should be easy enough to hardcode as exceptions since they shouldn't vary across projects. The other executable files are:

- `chrome_crashpad_handler`
- `chrome-sandbox`
- any files ending in `.so`

But I still don't know how to determine whether a file is executable from Node - only via `ls -al` right now.

**Comment by jjeff** [comment]
I went with the "parse the package.json file and assume that the executable is named using `productName` (with a fallback of `name`)". [Here's the pull request.](https://github.com/spaceagetv/electron-playwright-helpers/pull/26). It's passing the Ubuntu-based CI tests, so it's still finding the executable in a Linux Electron Forge build.

HOWEVER, by "fixing" this, I'm going to be **"breaking"** things for those of you who have implemented workarounds. I'm hesitant to mark this as a BREAKING CHANGE though… 'cause it's technically a "fixing" change.

**Comment by Slapbox** [comment]
I think the `fs.access` method I linked is likely to be a lot more reliable.

For example, in our app, the executable name can vary between `app` and `app-dev`. 

Any executable file ending in `.so` or starting with `chrome` could be excluded and then it'd presumably always find the right file as the only remaining executable. I haven't tested many versions of Electron though since it was just some quick research.

But any PR is welcome!

**Comment by jjeff** [comment]
> I think the `fs.access` method I linked is likely to be a lot more reliable.
> 
> For example, in our app, the executable name can vary between `app` and `app-dev`.

/me comically shakes his fist at Linus Torvalds

You're right. Even in my own app, we append the name for dev versions. Okay. I'll update the PR…

Thanks for the feedback! Super helpful.

**Comment by jjeff** [comment]
Okay! New method:
```TS
if (platform === 'linux') {
    // Linux Structure
    // <buildDir>/
    //   <appName> (executable)
    //   resources/
    //     app.asar (asar bundle) - or -
    //     app --- (untested - we're making assumptions here)
    //       package.json
    //       (your app structure)

    const list = fs.readdirSync(buildDir)
    const exeCandidates = list.filter((fileName) => {
      // Assume the executable is the only file in the directory that...
      // ...does not have one of these suffixes
      const ignoreSuffixes = ['.so', '.bin', '.pak', '.dat', '.json']
      // ...does not have one of these names
      const ignoreNames = ['resources', 'locales']
      // ...does not start with one of these names
      const ignoreStartsWith = ['chrome', 'lib', 'LICENSE']

      if (ignoreSuffixes.some((suffix) => fileName.endsWith(suffix))) {
        return false
      }
      if (ignoreNames.some((name) => fileName === name)) {
        return false
      }
      if (ignoreStartsWith.some((name) => fileName.startsWith(name))) {
        return false
      }
      const filePath = path.join(buildDir, fileName)
      const stats = fs.statSync(filePath)

      // ...is not a directory
      if (stats.isDirectory()) {
        return false
      }

      // ...is not a symlink
      if (stats.isSymbolicLink()) {
        return false
      }

      // ...is executable
      try {
        fs.accessSync(filePath, fs.constants.X_OK)
        return true
      } catch (err) {
        return false
      }
    })
    if (exeCandidates.length > 1) {
      console.warn(
        `Found ${exeCandidates.length} executable files in ${buildDir}. Will use ${exeCandidates[0]}.`
      )
    }
    if (exeCandidates.length < 1) {
      throw new Error(
        `Could not find executable file in ${buildDir}. Please check your build directory. If file exists, please make sure it is executable. If file is executable, please file an issue at https://github.com/spaceagetv/electron-playwright-helpers/issues.`
      )
    }
    executable = path.join(buildDir, exeCandidates[0])
```

**Comment by Slapbox** [comment]
I only did a quick once over, but I think that solution looks good!

Reading all the code it takes to support this simple thing on Linux really drives home:

> comically shakes his fist at Linus Torvalds

Thanks again for your great work!

**Comment by MatthijsBurgh** [comment]
Sorry guys I wasn't able to contribute. I will check the new code soon.

**Comment by MatthijsBurgh** [comment]
Yes, it does work. Though I keep experiencing an issue when using electron in a `jest` test environment. But that is another issue and not related to this project.
